server.port=8080
spring.application.name=system
# Kết nối Database
spring.datasource.url=jdbc:mysql://localhost:3306/logistics_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=thuctd2k5@ZZ

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# EMAIL CONFIGURATION (SMTP)
# ===============================
# Server của Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
app.admin.email=vmh36999@gmail.com
app.admin.password=admin123
# Nên dùng biến môi trường: ${MAIL_USERNAME} thay vì ghi thẳng email vào đây
spring.mail.username=vmh36999@gmail.com
# Đây là "App Password", KHÔNG PHẢI mật khẩu đăng nhập Gmail thông thường
spring.mail.password=fxov atbl mcmn nlgo
# Email gửi đi mặc định
spring.mail.from=vmh36999@gmail.com

# Các thuộc tính bổ sung để đảm bảo kết nối an toàn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===============================
# THYMELEAF CONFIG (Cho Email Template)
# ===============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Cho phép chạy @Async (Gửi mail không đợi)
spring.main.allow-bean-definition-overriding=true

# Shipping fee configuration
shipping.base-weight-limit=1.0
shipping.extra-weight-unit=0.5
shipping.price-per-extra-unit=5000

shipping.fee.intra-region=15000
shipping.fee.inter-region-near=30000
shipping.fee.inter-region-far=50000

// Cache configuration
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
// Payment configuration
payment.momo.partner-code=MOMOLRJZ20181206
payment.momo.access-key=mTCKt9W3eU1m39TW
payment.momo.secret-key=SetA5RDnLHvt51AULf51DyauxUo3kDU6
payment.momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
payment.momo.return-url=https://nonextenuating-ungreeted-jenny.ngrok-free.dev/api/payments/momo-callback
payment.momo.notify-url=https://nonextenuating-ungreeted-jenny.ngrok-free.dev/api/payments/momo-ipn
payment.momo.refund-endpoint=https://test-payment.momo.vn/v2/gateway/api/refund

